### ISSUE TITLE
Improve blob detection in import

### ISSUE THREAD

**Issue by pfrazee** [arj03/ssb-exporter#1]
Blobs can be referenced in more places than just `mentions`. (The way links work in SSB is, any attribute on the top-level of the `content` object can be a link, if the value is either a valid [ssb-ref](https://scuttlebot.io/apis/modules/ssb-ref.html), or an object with a valid ssb-ref `.link` attribute; the keyname of the link is the "relation", like the `rel` attribute in `<link>` elements of html.)

I recommend you use [indexLinks](https://scuttlebot.io/apis/modules/ssb-msgs.html#indexlinks) to accurately find all blob-links.

**Comment by arj03** [comment]
Thanks, I'll have a look at that
